apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3                          # Number of pod replicas
  selector:
    matchLabels:
      app: backend                     # Label selector for pods
  template:
    metadata:
      labels:
        app: backend                   # Labels applied to pods
    spec:
      containers:
      - name: backend-container
        image: testingkyaw/my-python-app:v2  # Container image
        ports:
        - containerPort: 8000         # Port exposed by container
        env:                        # Environment variables (optional)
        - name: FLASK_DEBUG
          value: "1"
        - name: FLASK_APP
          value: "run.py"
        - name: DATABASE_URL
          value: "postgresql://ciscobase.cds1wi0qiwop.us-east-1.rds.amazonaws.com:postgres@Cisco123:5432/app"
        - name: SECRET_KEY
          value: "your-secret-key-here"
        - name: DB_HOST
          value: "ciscobase.cds1wi0qiwop.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "app"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "Cisco123"
        - name: ALLOWED_ORIGINS
          value: "http://localhost:3000,http://localhost:80"       
        resources:                   # Resource requests/limits (optional)
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

